### ISSUE TITLE
Wiring schema

### ISSUE THREAD

**Issue by nexana** [ScottyDoesKnow/raspi-pn532-v2#2]
Hi,

How can I know what wiring schema to use?
I cannot seem to find it anywhere in the linked documentation.

Kind regards, and appreciate your help!

**Comment by ScottyDoesKnow** [comment]
Can you be more specific? It should be easy to find which pins on your Pi do I2C/SPI/Serial, and there's a table in the PN532 document that tells you which pins to use for each connection type.

**Comment by nexana** [comment]
I've been through the documentation but it's unclear to me wichh pin for the NFC pn532 module to which GPIO pin of my raspberry PI3.

I've tried following the wiring schematic on the tutorial in this link but it is for a python script (see the second image)
https://learn.adafruit.com/raspberry-pi-nfc-minecraft-blocks/hardware-wiring
It fully works for that script, but not for the library in this codebase.

So I am wondering if the wiring should be different for your library?

**Comment by ScottyDoesKnow** [comment]
Not sure how much I can help you there. That's a different board than I used, so not sure on the wiring. And the tutorial is using SPI, which is the connection type I couldn't get working.
